fix: invalid argument for conda env creation

diff --git a/.github/workflows/test_binding.yml b/.github/workflows/test_binding.yml
--- a/.github/workflows/test_binding.yml
+++ b/.github/workflows/test_binding.yml
@@ -11,13 +11,11 @@ jobs:
     runs-on: macOS-latest
     steps:
       - name: Checkout
-        uses: actions/checkout@v4
+        uses: actions/checkout@v3
 
       - name: activate environment
         uses: conda-incubator/setup-miniconda@v2
         with:
-          auto-update-conda: true
-          auto-update-micromamba: true
           environment-file: environment.yml
           activate-environment: pybind11-env
         
@@ -35,6 +33,8 @@ jobs:
         
       - name: add small badge (of course ;))
         run: |
-          echo "![small badge](https://img.shields.io/badge/pybind11%20test-passing-brightgreen)"
-          echo "![small badge](https://img.shields.io/badge/pybind11%20test-failing-red)"
-          echo "![small badge](https://img.shields.io/badge/pybind11%20test-unknown-lightgrey)"
+          if [ $? -eq 0 ]; then
+            echo "![small badge](https://img.shields.io/badge/pybind11%20test-passing-brightgreen)"
+          else
+            echo "![small badge](https://img.shields.io/badge/pybind11%20test-failing-red)"
+          fi
